### PR TITLE
RTV Plugin Compatibility

### PR DESCRIPTION
**Pull request by nickj609**
Hey there! Wanted to start off by saying thank you for this awesome modded server. You definitely saved me a ton of time. I was hoping to do the same for you. I developed a plugin that dynamically updates the maplist.txt file based on the current map group. It essentially replaces the Ultimate Map Chooser plugin that you created and uses the same css_mapgroup cvar. 

Below is a link to the source code for this plugin:

https://github.com/nickj609/GameModeManager

Let me know your thoughts!

### CODE REVIEW

**Comment by kus** [comment]
Hey @nickj609 thank you.

This certainly looks promising. You’ve built all the features I planned to build.

I’ll take a look at trial running it on my server in the next couple of days.

**Comment by mavproductions** [comment]
Please keep !map functionality the way it is if possible. I did a quick search and couldn't find !map mentioned in the code.

**Comment by nickj609** [comment]
@mavproductions  I actually used the !maps command instead (also referred to as css_maps in the repo), although I can update it to accommodate this request if needed. I am actually using a separate SimpleAdmin plugin that has a !map command that conflicts which is why I used this alternative.

**Comment by mavproductions** [comment]
You're right about SimpleAdmin. My mistake. I just enjoy having people able to use !map the way simple admin handles it. If you can accommodate that would be really nice of you and appreciated, but no worries if you think it should be out of scope instead.

**Comment by mavproductions** [comment]
@nickj609 I'm trying to test from your repo and am running into issues with the plugin being stuck in a "[LOADING]" state in my `css_plugins list`

I think I might know the issue, but mind humoring me by looking at my personal [gamemodes_server.txt](https://github.com/mavproductions/cs2-modded-server/blob/master/game/csgo/gamemodes_server.txt) to see if there would be issues querying the maps/modes?

Hoping it's a simple fix!

**Comment by mavproductions** [comment]
`From log-cssharp.txt`

> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Exception: Cannot find 'RTVPlugin': /home/steam/cs2/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/RockTheVote.dll
>    at GameModeManager.Plugin.OnConfigParsed(Config config) in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Config.cs:line 22
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 339
>    at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 217
>    at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
>    at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

**Comment by mavproductions** [comment]
Tried to set `ListEnabled` to 0 and I still get similar problems:

2024-03-28 13:43:39.720 +00:00 [INFO] plugin:GameModeManager OnMapsCommand execution started
2024-03-28 14:20:07.199 +00:00 [INFO] plugin:GameModeManager OnModesCommand execution started
2024-03-28 14:20:22.025 +00:00 [INFO] plugin:GameModeManager OnMapsCommand execution started
2024-03-28 14:20:54.353 +00:00 [INFO] plugin:GameModeManager OnMapGroupCommand execution started
2024-03-28 14:20:54.353 +00:00 [INFO] plugin:GameModeManager Map group command detected!
2024-03-28 14:20:54.354 +00:00 [INFO] plugin:GameModeManager Current MapGroup is .
2024-03-28 14:20:54.355 +00:00 [INFO] plugin:GameModeManager New MapGroup is .
2024-03-28 14:20:54.355 +00:00 [INFO] plugin:GameModeManager Mapgroup is the same. Not updating map list...
2024-03-28 14:21:00.794 +00:00 [INFO] plugin:GameModeManager OnMapsCommand execution started

**Comment by nickj609** [comment]
@mavproductions, thanks for bringing this to my attention. I have one other report of this behavior. I am going to do some thorough testing tomorrow afternoon (EST) and will report back here with an update.

**Comment by mavproductions** [comment]
Amazing. Thank you, and look forward to a hopeful solution!

**Comment by mavproductions** [comment]
Any updates?

**Comment by nickj609** [comment]
@mavproductions, not sure why, but when I remove and recreate this section manually in your gamemodes_server.txt the issue disappears.

```
"mg_retakes"
{
	"name"			"mg_retakes"
	"maps"
	{
		"de_ancient"		""
		"de_anubis"			""
		"de_dust2"			""
		"de_inferno"		""
		"de_mirage"			""
		"de_nuke"			""
		"de_overpass"		""
		"de_vertigo			""
	}
}
```

Maybe there are some non-ASCII characters in there or something. Also, it's worth mentioning that if you have the Ultimate Map Chooser plugin installed, you will need to remove it.

**Comment by mavproductions** [comment]
> "mg_retakes"
> {
> 	"name"			"mg_retakes"
> 	"maps"
> 	{
> 		"de_ancient"		""
> 		"de_anubis"			""
> 		"de_dust2"			""
> 		"de_inferno"		""
> 		"de_mirage"			""
> 		"de_nuke"			""
> 		"de_overpass"		""
> 		"de_vertigo			""
> 	}
> }

Tried playing around with it and no luck. How long should it take for the plugin status to go from [LOADING] to [LOADED] status normally? Instantly?

when I type css_maps, that definitely registers as `[INFO] (plugin:GameModeManager) OnMapsCommand execution started` appears.

Also:
image
image

Just doesn't make sense what's going on really for me. Are you sure the mg_retakes issue wasn't coincidence?

**Comment by nickj609** [comment]
@mavproductions, throughout my testing I used an exact copy of this pull request and everything worked smoothly. When using your gamemodes_server.txt file, I received an invalid VDF data error message, indicating that your gamemodes_server.txt file is not formatted properly in valve data format.

Anytime you see that the new map group is empty, its a pretty good indication that plugin was unable to parse this file and generate an array of map groups.  If you swap out your gamemodes_server.txt file with the original, do you experience the same behavior?

**Comment by mavproductions** [comment]
image
on kus gamemodes_server.txt

**Comment by mavproductions** [comment]
Same issue with kus' `gamemodes_server.txt`

Any chance we can move this convo to Discord? `__mav__`

If not, perhaps my versions of MM and CSS need changes? I've been holding off the newest versions since retakes has a few reported bugs with CSS v200+

**Comment by mavproductions** [comment]
Also, on your repo it doesn't mention RockTheVote as a required plugin, but I get this error `Cannot find 'RTVPlugin': /home/steam/cs2/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/RockTheVote.dll`

**Comment by mavproductions** [comment]
If I load and unload the plugin (which might not matter) this is what I get
```16:53:31 [INFO] (cssharp:PluginContext) Loading plugin GameModeManager
16:53:31 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: Cannot find 'RTVPlugin': /home/steam/cs2/game/csgo/addons/counterstrikesharp/plugins/RockTheVote/RockTheVote.dll
   at GameModeManager.Plugin.OnConfigParsed(Config config) in C:\Users\nickj\OneDrive\Documents\CS2\plugins\GameModeManager\Config.cs:line 22
   at InvokeStub_Plugin.OnConfigParsed(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at CounterStrikeSharp.API.Core.BasePlugin.InitializeConfig(Object instance, Type pluginType) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/BasePlugin.cs:line 339
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 217
   at CounterStrikeSharp.API.Core.Application.OnCSSPluginCommand(CCSPlayerController caller, CommandInfo info) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Application.cs:line 189
   at CounterStrikeSharp.API.Core.Commands.CommandManager.HandleCommandInternal(Int32 playerSlot, IntPtr commandInfo) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Commands/CommandManager.cs:line 159
   at InvokeStub_Action`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120```

**Pull request closed without merging**
