### PR TITLE
Add Docker Implementation

### PR DESCRIPTION
**Pull request by DanielDKnudsen**
Add feature #59 and Addresses Discussion #25.

As for the issues with Docker discussed in #11, I have personally not had any issues when using a volume mounted to the container as well as running it in linux using WSL2.

This should feature should also make the setup of GCP instance, Linux and Windows a lot simpler - if they have Docker installed.

### CODE REVIEW

**Comment by DanielDKnudsen** [comment]
@kus I've now refactored this PR a bit. 

It is now working without issues. Feel free to merge/give feedback if something should be changed.

**Comment by weeestar** [comment]
Tested on Docker for Mac, and its working very well :)

**Comment by kus** [comment]
Thanks for the effort put into this @DanielDKnudsen

**Comment by tklostermannNSD** [comment]
Still doesnt work for me... checkout, .env properties, docker build, docker compose up and after the game DL this:

```
dlopen failed trying to load:
steamclient.so
with error:
steamclient.so: cannot open shared object file: No such file or directory
dlopen failed trying to load:
/home/steam/.steam/sdk64/steamclient.so
with error:
/home/steam/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Failed to load module '/home/steam/.steam/sdk64/steamclient.so'
 0 Failed to initialize Steamworks SDK for gameserver.  Failed to load module '/home/steam/.steam/sdk64/steamclient.so'
...
SteamGameServer_Init()
Failed to initialize Steamworks SDK for gameserver.  Failed to load module '/home/steam/.steam/sdk64/steamclient.so'
/home/cs2-modded-server/install_docker.sh: line 207:   264 Segmentation fault      sudo -u $user /home/steam/cs2/game/bin/linuxsteamrt64/cs2 -dedicated -console -usercon -autoupdate -tickrate $TICKRATE $IP_ARGS -port $PORT +map de_dust2 -maxplayers $MAXPLAYERS -authkey $API_KEY +sv_setsteamaccount $STEAM_ACCOUNT +game_type 0 +game_mode 0 +mapgroup mg_active
```

**Pull request merged**
