### PR TITLE
Updating docker flow

### LINKED ISSUE #140: [Bug]:  Failed to install app 730
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

No mod

### Are you trying to host online or on LAN?

Online on a cloud host Google, AWS, Azure etc (please specify host)

### Metamod:Source Version

i don't know that yet

### Metamod:Source Plugins loaded

i don't know that yet

### CounterStrikeSharp Version

i don't know that yet

### CounterStrikeSharp Plugins loaded

i don't know that yet

### What is the bug

I did all the steps for using docker, but now im getting this error when doing `# docker-compose up`

### Game console output

_No response_

### Server log output

```shell
Recreating cs2-modded-server ... done
Attaching to cs2-modded-server
cs2-modded-server    | Starting on Debian GNU/Linux: 11...
cs2-modded-server    | With   88 Gb free space...
cs2-modded-server    | Checking steam user exists...
cs2-modded-server    | Checking steamcmd exists...
cs2-modded-server    | --2024-06-23 22:17:22--  https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
cs2-modded-server    | Resolving steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)... 92.122.218.120, 92.122.218.152
cs2-modded-server    | Connecting to steamcdn-a.akamaihd.net (steamcdn-a.akamaihd.net)|92.122.218.120|:443... connected.
cs2-modded-server    | HTTP request sent, awaiting response... 200 OK
cs2-modded-server    | Length: 2428561 (2.3M) [application/octet-stream]
cs2-modded-server    | Saving to: 'steamcmd_linux.tar.gz'
cs2-modded-server    | 
cs2-modded-server    |      0K .......... .......... .......... .......... ..........  2% 9.95M 0s
cs2-modded-server    |     50K .......... .......... .......... .......... ..........  4% 34.7M 0s
cs2-modded-server    |    100K .......... .......... .......... .......... ..........  6% 9.25M 0s
cs2-modded-server    |    150K .......... .......... .......... .......... ..........  8% 10.8M 0s
cs2-modded-server    |    200K .......... .......... .......... .......... .......... 10% 35.8M 0s
cs2-modded-server    |    250K .......... .......... .......... .......... .......... 12% 17.1M 0s
cs2-modded-server    |    300K .......... .......... .......... .......... .......... 14% 51.5M 0s
cs2-modded-server    |    350K .......... .......... .......... .......... .......... 16% 26.9M 0s
cs2-modded-server    |    400K .......... .......... .......... .......... .......... 18% 41.1M 0s
cs2-modded-server    |    450K .......... .......... .......... .......... .......... 21% 53.8M 0s
cs2-modded-server    |    500K .......... .......... .......... .......... .......... 23% 50.8M 0s
cs2-modded-server    |    550K .......... .......... .......... .......... .......... 25%  114M 0s
cs2-modded-server    |    600K .......... .......... .......... .......... .......... 27% 57.7M 0s
cs2-modded-server    |    650K .......... .......... .......... .......... .......... 29% 94.1M 0s
cs2-modded-server    |    700K .......... .......... .......... .......... .......... 31% 67.3M 0s
cs2-modded-server    |    750K .......... .......... .......... .......... .......... 33%  174M 0s
cs2-modded-server    |    800K .......... .......... .......... .......... .......... 35% 73.8M 0s
cs2-modded-server    |    850K .......... .......... .......... .......... .......... 37% 97.3M 0s
cs2-modded-server    |    900K .......... .......... .......... .......... .......... 40% 81.8M 0s
cs2-modded-server    |    950K .......... .......... .......... .......... .......... 42% 54.9M 0s
cs2-modded-server    |   1000K .......... .......... .......... .......... .......... 44%  152M 0s
cs2-modded-server    |   1050K .......... .......... .......... .......... .......... 46%  152M 0s
cs2-modded-server    |   1100K .......... .......... .......... .......... .......... 48% 97.0M 0s
cs2-modded-server    |   1150K .......... .......... .......... .......... .......... 50%  155M 0s
cs2-modded-server    |   1200K .......... .......... .......... .......... .......... 52%  167M 0s
cs2-modded-server    |   1250K .......... .......... .......... .......... .......... 54%  117M 0s
cs2-modded-server    |   1300K .......... .......... .......... .......... .......... 56% 99.6M 0s
cs2-modded-server    |   1350K .......... .......... .......... .......... .......... 59%  210M 0s
cs2-modded-server    |   1400K .......... .......... .......... .......... .......... 61%  165M 0s
cs2-modded-server    |   1450K .......... .......... .......... .......... .......... 63%  159M 0s
cs2-modded-server    |   1500K .......... .......... .......... .......... .......... 65%  170M 0s
cs2-modded-server    |   1550K .......... .......... .......... .......... .......... 67%  139M 0s
cs2-modded-server    |   1600K .......... .......... .......... .......... .......... 69%  183M 0s
cs2-modded-server    |   1650K .......... .......... .......... .......... .......... 71%  151M 0s
cs2-modded-server    |   1700K .......... .......... .......... .......... .......... 73%  156M 0s
cs2-modded-server    |   1750K .......... .......... .......... .......... .......... 75%  135M 0s
cs2-modded-server    |   1800K .......... .......... .......... .......... .......... 78%  166M 0s
cs2-modded-server    |   1850K .......... .......... .......... .......... .......... 80%  137M 0s
cs2-modded-server    |   1900K .......... .......... .......... .......... .......... 82%  157M 0s
cs2-modded-server    |   1950K .......... .......... .......... .......... .......... 84%  126M 0s
cs2-modded-server    |   2000K .......... .......... .......... .......... .......... 86%  148M 0s
cs2-modded-server    |   2050K .......... .......... .......... .......... .......... 88%  125M 0s
cs2-modded-server    |   2100K .......... .......... .......... .......... .......... 90%  156M 0s
cs2-modded-server    |   2150K .......... .......... .......... .......... .......... 92%  139M 0s
cs2-modded-server    |   2200K .......... .......... .......... .......... .......... 94%  142M 0s
cs2-modded-server    |   2250K .......... .......... .......... .......... .......... 96%  158M 0s
cs2-modded-server    |   2300K .......... .......... .......... .......... .......... 99%  139M 0s
cs2-modded-server    |   2350K .......... .......... .                               100%  223M=0.04s
cs2-modded-server    | 
cs2-modded-server    | 2024-06-23 22:17:22 (56.7 MB/s) - 'steamcmd_linux.tar.gz' saved [2428561/2428561]
cs2-modded-server    | 
cs2-modded-server    | steamcmd.sh
cs2-modded-server    | linux32/steamcmd
cs2-modded-server    | linux32/steamerrorreporter
cs2-modded-server    | linux32/libstdc++.so.6
cs2-modded-server    | linux32/crashhandler.so
cs2-modded-server    | Downloading any updates for CS2...
cs2-modded-server    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
cs2-modded-server    | ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
cs2-modded-server    | [  0%] Checking for available update...
cs2-modded-server    | [----] Downloading update (0 of 58905 KB)...
cs2-modded-server    | [  0%] Downloading update (0 of 58905 KB)...
cs2-modded-server    | [  0%] Downloading update (0 of 58905 KB)...
cs2-modded-server    | [  0%] Downloading update (3132 of 58905 KB)...
cs2-modded-server    | [  5%] Downloading update (6935 of 58905 KB)...
cs2-modded-server    | [ 11%] Downloading update (9567 of 58905 KB)...
cs2-modded-server    | [ 16%] Downloading update (11872 of 58905 KB)...
cs2-modded-server    | [ 20%] Downloading update (14593 of 58905 KB)...
cs2-modded-server    | [ 24%] Downloading update (16997 of 58905 KB)...
cs2-modded-server    | [ 28%] Downloading update (19410 of 58905 KB)...
cs2-modded-server    | [ 32%] Downloading update (21748 of 58905 KB)...
cs2-modded-server    | [ 36%] Downloading update (24275 of 58905 KB)...
cs2-modded-server    | [ 41%] Downloading update (26605 of 58905 KB)...
cs2-modded-server    | [ 45%] Downloading update (28978 of 58905 KB)...
cs2-modded-server    | [ 49%] Downloading update (31362 of 58905 KB)...
cs2-modded-server    | [ 53%] Downloading update (33886 of 58905 KB)...
cs2-modded-server    | [ 57%] Downloading update (36209 of 58905 KB)...
cs2-modded-server    | [ 61%] Downloading update (38648 of 58905 KB)...
cs2-modded-server    | [ 65%] Downloading update (41289 of 58905 KB)...
cs2-modded-server    | [ 70%] Downloading update (42464 of 58905 KB)...
cs2-modded-server    | [ 72%] Downloading update (43687 of 58905 KB)...
cs2-modded-server    | [ 74%] Downloading update (45000 of 58905 KB)...
cs2-modded-server    | [ 76%] Downloading update (46289 of 58905 KB)...
cs2-modded-server    | [ 78%] Downloading update (47515 of 58905 KB)...
cs2-modded-server    | [ 80%] Downloading update (48731 of 58905 KB)...
cs2-modded-server    | [ 82%] Downloading update (50055 of 58905 KB)...
cs2-modded-server    | [ 84%] Downloading update (51276 of 58905 KB)...
cs2-modded-server    | [ 87%] Downloading update (52497 of 58905 KB)...
cs2-modded-server    | [ 89%] Downloading update (53810 of 58905 KB)...
cs2-modded-server    | [ 91%] Downloading update (55026 of 58905 KB)...
cs2-modded-server    | [ 93%] Downloading update (56163 of 58905 KB)...
cs2-modded-server    | [ 95%] Downloading update (57442 of 58905 KB)...
cs2-modded-server    | [ 97%] Downloading update (58669 of 58905 KB)...
cs2-modded-server    | [ 99%] Downloading update (58905 of 58905 KB)...
cs2-modded-server    | [100%] Download Complete.
cs2-modded-server    | [----] Applying update...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Cleaning up...
cs2-modded-server    | [----] Update complete, launching...
cs2-modded-server    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
cs2-modded-server    | Logging directory: '/home/steam/Steam/logs'
cs2-modded-server    | [  0%] Checking for available updates...
cs2-modded-server    | [----] Verifying installation...
cs2-modded-server    | [  0%] Downloading update...
cs2-modded-server    | [  0%] Checking for available updates...
cs2-modded-server    | [----] Download complete.
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Extracting package...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Installing update...
cs2-modded-server    | [----] Cleaning up...
cs2-modded-server    | [----] Update complete, launching Steamcmd...
cs2-modded-server    | UpdateUI: skip show logosteamcmd.sh[29]: Restarting steamcmd by request...
cs2-modded-server    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
cs2-modded-server    | Logging directory: '/home/steam/Steam/logs'
cs2-modded-server    | [  0%] Checking for available updates...
cs2-modded-server    | [----] Verifying installation...
cs2-modded-server    | UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1718904263
cs2-modded-server    | -- type 'quit' to exit --
cs2-modded-server    | Loading Steam API...OK
cs2-modded-server    | Logging set (enabled/verbose).
cs2-modded-server    | "@sSteamCmdForcePlatformType" = "linux"
cs2-modded-server    | "@sSteamCmdForcePlatformBitness" = "64"
cs2-modded-server    | 
cs2-modded-server    | Connecting anonymously to Steam Public...OK
cs2-modded-server    | Waiting for client config...OK
cs2-modded-server    | Waiting for user info...OK
cs2-modded-server    | ERROR! Failed to install app '730' (Missing file permissions)
cs2-modded-server    | /home/user !!!!!!!
cs2-modded-server    | Installing mods
cs2-modded-server    | Merging in custom files
cs2-modded-server    | grep: game/csgo/gameinfo.gi: No such file or directory
cs2-modded-server    | awk: cannot open game/csgo/gameinfo.gi (No such file or directory)
cs2-modded-server    | game/csgo/gameinfo.gi successfully patched for Metamod.
cs2-modded-server    | Starting server on (server ip here):
cs2-modded-server    | ./game/bin/linuxsteamrt64/cs2 -dedicated -console -usercon -autoupdate -tickrate 128 -port +map de_dust2 -maxplayers 24```
```

### Steps to reproduce

1. Create a VM in Google Cloud
2. Do all the steps here
3. See error

### LINKED ISSUE #172: [Bug]: Docker Container
### Server is up to date

- [X] My server is up-to-date and I'm using the latest version of this mod from this github.

### I've followed the instructions

- [X] I've followed the instructions

### Game Server Login Token

- [X] I'm using a valid Game Server Login Token or running on LAN

### Operating System

Linux Ubuntu 22.04

### Which mod are you playing

Other (please specify)

### Are you trying to host online or on LAN?

Online off my machine

### Metamod:Source Version

na

### Metamod:Source Plugins loaded

na

### CounterStrikeSharp Version

na

### CounterStrikeSharp Plugins loaded

na

### What is the bug

Hi after a fresh docker installation the steamcmd fails with no permission to the directory.

`Connecting anonymously to Steam Public...OK

Waiting for client config...OK

Waiting for user info...OK

ERROR! Failed to install app '730' (Missing file permissions)

/home/user !!!!!!!

Installing mods

Merging in custom files

grep: game/csgo/gameinfo.gi: No such file or directory

game/csgo/gameinfo.gi successfully patched for Metamod.

Starting server on 81.169.194.72:

./game/bin/linuxsteamrt64/cs2 -dedicated -console -usercon -autoupdate -tickrate 128 -port +map de_dust2 -maxplayers 16 -authkey "EC35663049D0C22F8C691BCE8002A637" +sv_setsteamaccount "A17B5DB073F761EDF6DBFF3D259A42C3" +game_type 0 +game_mode 0 +mapgroup mg_active +sv_lan +sv_password +rcon_password +exec

awk: cannot open game/csgo/gameinfo.gi (No such file or directory)

sudo: /home/steam/cs2/game/bin/linuxsteamrt64/cs2: command not found`

### Game console output

_No response_

### Server log output

_No response_

### Steps to reproduce

1. build docker image on server
2. start with docker compose
3. error occurs.

### PR DESCRIPTION
**Pull request by phyzical**
* adds a workflow that will auto build and push to this repo for distribution
* fixes #140 by moving the chown
* fixes #172 
* simplifies the docker flow by using envs
* copys from repo during flow instead of re-cloning repo

i suggest review with ignore whitespace on

feel free to decline, im building it my end anyway

### CODE REVIEW

**Comment by AceKicker47** [comment]
> * adds a workflow that will auto build and push to this repo for distribution
> 
>     * fixes [[Bug]:  Failed to install app 730 #140](https://github.com/kus/cs2-modded-server/issues/140) by moving the chown
> 
>     * simplifies the docker flow by using envs
> 
>     * copys from repo during flow instead of re-cloning repo
> 
> 
> i suggest review with ignore whitespace on
> 
> feel free to decline, im building it my end anyway

can you help me? still not working even when use your repo feel like broken docker image
acekicker47#6161 discord

**Comment by phyzical** [comment]
@AceKicker47 what error do you get?

**Comment by JantsoP** [comment]
Can validate this PR. Used @phyzical repo to make my own server since I was hit by the Issue #140 
No changes done, just pure clone, set my own .env values and build image and run it.

**Comment by phyzical** [comment]
@kus anything you need to progress this through?

**Comment by kus** [comment]
@phyzical thanks for the work on docker. The Docker integration has been fully driven by the community.

Is there anything that should be added to the README are the instructions clear enough?

**Comment by phyzical** [comment]
@kus good point, there is some light docker readme. but i will add some more context now in a follow up pr

**Pull request merged**
