### PR TITLE
Add mods:Playermodelchanger & Multiaddonmanager

### PR DESCRIPTION
**Pull request by HuangQDZBC233**
Playermodelchanger allows players to add custom models into the server,and players can change them via in-game chat menu.

Multiaddonmanager is a addon allows server owners to use multiple workshop addons at once and have clients download them. It's also a requirement of Playermodelchanger if people want to use playermodels that uploaded on workshop.

I've also added config files of these mods,allowing users to configure them right away.

Detailed information:
Playermodelchanger:https://github.com/samyycX/CS2-PlayerModelChanger?tab=readme-ov-file
Multiaddonmanager:https://github.com/Source2ZE/MultiAddonManager

(Dunno if mod adding request is allowed,as I do not made these mods,but it will be great for server owners to add playermodels conveniently)

### CODE REVIEW

**Comment by mavproductions** [comment]
Hey @HuangQDZBC233, 

While this app is nice(and I have tested it), this will require further documentation about how players must use this if @kus decides to add this in. Without proper documentation, we risk users getting [GSLT bans](https://blog.counter-strike.net/index.php/server_guidelines/) on their accounts that they care about.

The process for server ops to use workshop tools to integrate their own custom models introduces some further complexity to the cs2-modded-server setup, which I believe @kus has purposefully made this repo for 1-touch install style procedures/simplicity. I wouldn't mind helping with documentation, but this is an app that as well is kind of glitchy in nature, and can cause servers to crash, due to [Precache issues](https://github.com/samyycX/CS2-PlayerModelChanger?tab=readme-ov-file#known-issues) among other things.

**Comment by HuangQDZBC233** [comment]
I understand the risk.And I just came up with another solution.
These mods don't need to be added to the server files,but to put them in a different folder that the server won't load the addon until they copy the mod files into the server files.
We just need to clarify the risk.

**Comment by mavproductions** [comment]
> I understand the risk.And I just came up with another solution. These mods don't need to be added to the server files,but to put them in a different folder that the server won't load the addon until they copy the mod files into the server files. We just need to clarify the risk.

I understand this as well, but you're not acknowledging some other security implications about adding this feature.

**Comment by HuangQDZBC233** [comment]
> > I understand the risk.And I just came up with another solution. These mods don't need to be added to the server files,but to put them in a different folder that the server won't load the addon until they copy the mod files into the server files. We just need to clarify the risk.
> 
> I understand this as well, but you're not acknowledging some other security implications about adding this feature.

I guess so.There's a lot of things that I didn't understand.
I think I better close it.

**Pull request closed without merging**
